# Generated by Django 3.0.6 on 2020-05-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=models.TimeField(default='IST'),
        ),
    ]
