# Generated by Django 3.0.6 on 2020-05-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200517_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=models.CharField(max_length=20),
        ),
    ]
