# Generated by Django 3.0.6 on 2020-05-17 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200517_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='activity',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='app.member'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.CharField(max_length=30),
        ),
    ]
